server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://45.77.135.239:3306/tb_hotel?useSSL=false
    username: root
    password: tw.662531
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo